export const SET_CURRENT_TARGET = "SET_CURRENT_TARGET";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const GET_USER_ENTRIES = "GET_USER_ENTRIES";
export const GET_INBOX_ENTRIES = "GET_INBOX_ENTRIES";
export const SET_LOGIN_ERRORS = "SET_LOGIN_USERNAME_ERRORS";
export const CLEAR_LOGIN_ERRORS = "CLEAR_LOGIN_ERRORS";
