export const SET_CURRENT_TARGET = "SET_CURRENT_TARGET";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const GET_USER_ENTRIES = "GET_USER_ENTRIES";
